/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FrButton {
        /**
          * Text to be present on the button
         */
        "text": string;
    }
}
declare global {
    interface HTMLFrButtonElement extends Components.FrButton, HTMLStencilElement {
    }
    var HTMLFrButtonElement: {
        prototype: HTMLFrButtonElement;
        new (): HTMLFrButtonElement;
    };
    interface HTMLElementTagNameMap {
        "fr-button": HTMLFrButtonElement;
    }
}
declare namespace LocalJSX {
    interface FrButton {
        /**
          * Text to be present on the button
         */
        "text"?: string;
    }
    interface IntrinsicElements {
        "fr-button": FrButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fr-button": LocalJSX.FrButton & JSXBase.HTMLAttributes<HTMLFrButtonElement>;
        }
    }
}
